# Generated by Django 3.0.7 on 2020-06-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=500)),
                ('price', models.IntegerField(default=1)),
                ('address', models.CharField(max_length=260)),
                ('period', models.TimeField()),
            ],
        ),
    ]
