# Generated by Django 3.0.7 on 2020-07-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zper_api', '0006_auto_20200706_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='endpoint',
            field=models.URLField(default='http://example.com/premium/content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(),
        ),
    ]
